### ISSUE TITLE
Loading plot/vega starts chrome browser

### ISSUE THREAD

**Issue by Symbolics** [Lisp-Stat/plot#20]
Just _loading_ the system via ASDF causes the chrome browser to be displayed.  It appears to be caused by the `executable-present-p` function? I assume this behaviour is not intentional?

**Comment by tobyWorland** [comment]
@Symbolics Which platform? The only thing I can think of is that chrome on Windows might not treat the version command line argument the same as Linux does.

**Comment by Symbolics** [comment]
It's on Windows.

**Comment by tobyWorland** [comment]
@Symbolics Please can you confirm if the pull request fixes it on your side.

**Comment by Symbolics** [comment]
Fixed, thanks.
