### ISSUE TITLE
SEQ-MAX is undefined.

### ISSUE THREAD

**Issue by JosephBoyd** [Lisp-Stat/plot#23]
I am getting the following when running stem-and-leaf functions.

UNDEFINED-FUNCTION: The function PLOT/TEXT::SEQ-MAX is undefined.

I am running on an apple MacBook Pro M2.

**Comment by Symbolics** [comment]
Fixed in [bb34d36](https://github.com/Lisp-Stat/plot/commit/bb34d3656692a15be2e8ccb5f5d8727fbc1a720b).

You will need to pull from this repo to get the changes, or wait until Quicklisp is updated.
