### ISSUE TITLE
Vlime Swank crash when loading :plot/vega

### ISSUE THREAD

**Issue by vukv93** [Lisp-Stat/plot#25]
Hello, I am pretty new to Lisp, and currently I'm using Neovim with Vlime and Roswell with SBCL 2.3.9 as a development environment.
When I try loading plot/vega package using `(ql:quickload :plot/vega)`, I get the following error in the Vlime server output window:
```
  <INFO> [02:05:22] vlime-usocket - Control thread stopping: (:SWANK-DATA-ERROR "No policy for symbols as keys defined. Please check YASON:*SYMBOL-KEY-ENCODER*.")
;; swank:close-connection: end of file on #<SB-SYS:FD-STREAM for "socket 127.0.0.1:35825, peer: 127.0.0.1:41070" {1003696823}>
```
Running  `ros run --eval '(ql:quickload :plot/vega)'` loads the package successfully.
I also had no problem a while ago using vim-slime (which I think just sends expression text to an independent REPL in another Vim or Tmux window), so to me it seems like a Vlime- or Swank-specific issue.
Could you please give me some advice on how to debug this further?

**Comment by snunez1** [comment]
I suspect this is more likely a problem with an out of date version of PLOT.  Quicklisp as been slow to update lately, and there's been major version updates since the last Quicklisp release.

Try installing from source and see if that fixes the error.

**Comment by snunez1** [comment]
Did using the source from the git repo work for you?

**Comment by vukv93** [comment]
Just tried it and had the same problem. I think it is related to having some CL packages installed from Debian stable repositories, presumably very outdated. I will set up an environment with reasonably recent package versions and elaborate.

**Comment by vukv93** [comment]
It's something related to Swank client, seems like everything works when running directly in a REPL or using another Vim plugin for communication with it.
