### ISSUE TITLE
Cannot open browser on Windows

### ISSUE THREAD

**Issue by maacl** [Lisp-Stat/plot#7]
Following "Getting started" I get the below error. Looks like the Chrome path is invalid. On Windows 11 Chrome is installed in `Program Files`, not `Program Files (x86)\\` and the path should not contain double `\.`
```

* (plot:plot-from-file (vglt:save-plot 'cars-plot))

debugger invoked on a SIMPLE-ERROR in thread #<THREAD "main thread" RUNNING {10010B0523}>: Couldn't execute "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe": The system cannot find the file specified.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-EXT:RUN-PROGRAM "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" ("--user-data-dir=C:/Users/marti/AppData/Local/Temp/plot/chrome-data-G784" "--window-size=800,600" "--app=file:///C:/Users/marti/AppData/Local/Temp/plot/cars-plot.html") :ENV NIL :ENVIRONMENT NIL :WAIT NIL :SEARCH T :INPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :OUTPUT NIL :IF-OUTPUT-EXISTS :APPEND :ERROR NIL :IF-ERROR-EXISTS :APPEND :STATUS-HOOK NIL :EXTERNAL-FORMAT :UTF-8 :DIRECTORY NIL :ESCAPE-ARGUMENTS T)
0]
```

**Comment by maacl** [comment]
Thanks. `(setf (nth 0 plot:*browser-commands*) (cons :chrome #+win32 "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")) `works.

**Comment by Symbolics** [comment]
FYI, you can add that line to your `ls-init.lisp` [initialisation file](https://lisp-stat.dev/docs/getting-started/installation/#initialization-file) for a fix that will happen every time you load Lisp-Stat.

**Comment by maacl** [comment]
Thanks for the tip.

**Comment by maacl** [comment]
For others who might want to use the init file to fix this, please note you have to load the plot package first, ie. `(asdf:load-system :plot/vglt)`
